---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appModServer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: appModServer
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appModServer
spec:
  selector:
    app: appModServer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appModServer
  template:
    metadata:
      labels:
        app: appModServer
    spec:
      containers:
        - name: appModServer
          image: strongjz/appmod_server:$(VERSION)
          ports:
            - containerPort: 8080
