apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appmodserver
  labels:
    app: monolith
    spot: monolith
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: cloudnative.wtf
      http:
        paths:
          - path: /
            backend:
              serviceName: monolith
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appmodserver
spec:
  selector:
    app: appmodserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmodserver
  labels:
    app: appmodserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appmodserver
  template:
    metadata:
      labels:
        app: appmodserver
    spec:
      containers:
        - name: appmodserver
          image: strongjz/appmod_server:0.0.1
          ports:
            - containerPort: 8080
